# Generated by Django 4.1 on 2022-10-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
