# Generated by Django 4.1 on 2022-09-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsuser',
            name='id_user',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
