# Generated by Django 4.1 on 2022-09-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_opsuser_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsuser',
            name='id_user',
        ),
    ]
