# Generated by Django 4.1 on 2022-09-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_remove_opsuser_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
