# Generated by Django 4.1 on 2022-09-02 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_campaign_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.FileField(upload_to='leads/<django.db.models.fields.related.ForeignKey>')),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.campaign')),
            ],
        ),
    ]
