# Generated by Django 4.1 on 2022-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_alter_leadfile_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfile',
            name='leads',
            field=models.FileField(upload_to='lead/'),
        ),
    ]
