# Generated by Django 4.1 on 2022-09-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_remove_leadfile_id_leadfile_lead_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfile',
            old_name='lead_id',
            new_name='le_id',
        ),
    ]
