# Generated by Django 4.1 on 2022-09-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_rename_lead_id_leadfile_le_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfile',
            old_name='le_id',
            new_name='lead_id',
        ),
    ]
