# Generated by Django 4.1 on 2022-09-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_rename_le_id_leadfile_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
