# Generated by Django 4.1 on 2022-09-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('ops', '0013_campaign_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.clientuser'),
            preserve_default=False,
        ),
    ]
