# Generated by Django 4.1 on 2022-09-06 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_campaign_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='upload/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
