# Generated by Django 4.1 on 2022-10-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('ops', '0015_uploadfile_alter_campaign_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='heap',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='client.clientuser'),
        ),
    ]
