# Generated by Django 4.1 on 2022-12-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_alter_leadfile_options_heap_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='heap',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='heap',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
