# Generated by Django 4.1 on 2022-12-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_alter_campaign_options_alter_heap_options_heap_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
